spring:
  datasource:
    url: jdbc:h2:mem:ProjetoIntegradorDB
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

logging:
  file: 
    name: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    "[org.springframework.web]": ERROR
    "[org.hibernate]": ERROR
    "[br.com.dh.ClinicaOdotologica]": DEBUG

    
