spring:
  datasource:
    url: jdbc:h2:mem:ProjetoIntegradorDB
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        generate_statistics=true
      session:
        events.log.LOG_QUERIES_SLOWER_THAN_MS=1
  h2:
    console:
      enabled: true
      path: /h2
server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: never
logging:
  file:
    name: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    "[org.springframework.web]": ERROR
    "[org.hibernate]": ERROR
    "[br.com.dh.ClinicaOdotologica]": DEBUG


